### ISSUE TITLE
Unnecessary shouldComponentUpdate override?

### ISSUE THREAD

**Issue by fkuril** [RisingStack/react-way-immutable-flux#2]
`Component` class implements `shouldComponentUpdate`. `Cart` component extends `Component` and overrides `shouldComponentUpdate` with exact same code.
https://github.com/RisingStack/react-way-immutable-flux/blob/f0c1a79bf8afa690da04e47d3d18e42df2cd9624/src/app/components/Cart.js#L19-21

**Comment by hekike** [comment]
Good catch. I removed these in this pr.
https://github.com/RisingStack/react-way-immutable-flux/pull/4
