### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by carlosipe** [RisingStack/react-way-immutable-flux#3]
Using Jest CLI v0.4.13
 FAIL  src/app/components/**tests**/Cart.spec.js
Error: Worker process exited before responding! exit code: null, exit signal: SIGSEGV
stderr:

A worker process has quit unexpectedly! This is bad news, shutting down now!
npm ERR! Test failed.  See above for more details.

**Comment by ruudud** [comment]
Works for me.

Node version?

**Comment by hekike** [comment]
@carlosipe Check `travis.yaml` for which version it's working for sure:
https://github.com/RisingStack/react-way-immutable-flux/blob/master/.travis.yml
